FROM apache/airflow:2.9.0-python3.11

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
# If needed, force reinstall
#RUN pip install --no-cache-dir --force-reinstall --upgrade -r /tmp/requirements.txt

# If broken plugin, uncomment this:
# RUN pip install setuptools